### ISSUE TITLE
[HTTPD] "Live" pages

### ISSUE THREAD

**Issue by wipe2238** [rotators/sfall#1]
Allow creating file-like pages, where content is appended from external source(s), and not coming from page generator function. Intended use is to track debug messages in browser on monitor#1, while game is running fullscreen on monitor#2.

**Comment by ghost2238** [comment]
I think websockets are suitable for this, means the server can push messages and even script calls can push information. No need for polling for updates then either.

**Comment by ghost2238** [comment]
I think this can be closed, will be a huge waste of time to implement.

**Comment by wipe2238** [comment]
:(

**Comment by ghost2238** [comment]
Well, whole httpd thing was a mistake, better to write such things as SSL code and it'll be compatible with vanilla sfall instead of requiring rfall. With asm patches you can extend it for additional functionality.

Just my opinion, because I feel exactly zero motivation to do any more work on httpd stuff in rfall and I doubt anyone else want either.

**Comment by wipe2238** [comment]
Nah, HTTPD is great to have, we just shifted into other stuff and it doesn't get ~~much~~ any love right now.
I still want to implement my insane ideas at some point, so i'll stick to what we already have when/if finally working on it. Maybe "_show, not tell_" will motivate you, maybe not. We'll see :)
